---
- name: Install Docker and Portainer CE
  hosts: servers
  become: yes # run tasks as sudo
  tasks:
    - name: 1. Install prerequisites for Docker repository
      apt:
        name:
          - ca-certificates
          - curl
        state: present
        update_cache: yes

    - name: 2. Create directory for Docker GPG key
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: 3. Add Docker's official GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
        force: yes

    - name: 4. Add Docker repository to Apt sources
      apt_repository:
        repo: >-
          deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc]
          https://download.docker.com/linux/ubuntu
          {{ ansible_lsb.codename }} stable
        state: present
        filename: docker

    - name: 5. Install Docker Engine and related packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: 6. Ensure Docker service is started and enabled on boot
      service:
        name: docker
        state: started
        enabled: yes

    - name: 7. Add remote user to the 'docker' group
      user:
        name: "{{ ansible_user }}" # get user that is running the playbook
        groups: docker
        append: yes
      register: user_added_to_docker_group
      
    # - name: 8. Securely create temp file for initial admin password
    #   copy:
    #     content: "{{ portainer_initial_password }}"
    #     dest: /tmp/portainer_password.txt
    #     mode: '0600'
    #   when: portainer_initial_password is defined
    #   no_log: true # Avoids logging the password

    - name: 9. Create a volume for Portainer data
      docker_volume:
        name: portainer_data

    - name: 10. Deploy Portainer CE container
      docker_container:
        name: portainer
        image: "portainer/portainer-ce:{{ portainer_version | default('latest') }}"
        state: started
        restart_policy: always
        ports:
          - "8000:8000"
          - "9443:9443"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data
        command: "{{ '--admin-password-file /tmp/portainer_password.txt' if portainer_initial_password is defined else omit }}"

    # - name: 11. Clean up temporary password file
    #   file:
    #     path: /tmp/portainer_password.txt
    #     state: absent
    #   when: portainer_initial_password is defined

    - name: Print final status message
      debug:
        msg: "SUCCESS! Portainer is running at https://{{ ansible_host }}:9443. If user '{{ ansible_user }}' was added to the docker group, a re-login is required for changes to take effect."
      when: user_added_to_docker_group.changed