# ansible/evolution-api-installer/install_evolution_api.yml

---
- name: Install Evolution API and MongoDB via Docker
  hosts: servers
  become: yes
  vars_files:
    - vars/secrets.yml
  vars:
    app_network_name: "app_network"
    # Pastas no host para persistir os dados
    evolution_data_path: "/opt/evolution-api"
    mongodb_data_path: "/opt/mongodb-data"

  tasks:
    - name: 1. Install prerequisites for Ansible Docker modules
      apt:
        name:
          - python3-pip
          - python3-docker
        state: present
        update_cache: yes

    - name: 2. Create persistent data directories on the host
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ evolution_data_path }}/instances"
        - "{{ evolution_data_path }}/store"
        - "{{ mongodb_data_path }}"

    - name: 3. Ensure the shared application network exists
      community.docker.docker_network:
        name: "{{ app_network_name }}"
        state: present

    - name: 4. Deploy the MongoDB container
      community.docker.docker_container:
        name: mongodb
        image: "mongo:5.0"
        restart_policy: unless-stopped
        volumes:
          - "{{ mongodb_data_path }}:/data/db"
        networks:
          - name: "{{ app_network_name }}"
        env:
          MONGO_INITDB_ROOT_USERNAME: "{{ mongodb_root_user }}"
          MONGO_INITDB_ROOT_PASSWORD: "{{ mongodb_root_password }}"
      no_log: true

    - name: 5. Deploy the Evolution API container
      community.docker.docker_container:
        name: evolution-api
        image: "atendai/evolution-api:latest"
        restart_policy: unless-stopped
        ports:
          - "8080:8080"
        volumes:
          - "{{ evolution_data_path }}/instances:/evolution/instances"
          - "{{ evolution_data_path }}/store:/evolution/store"
        networks:
          - name: "{{ app_network_name }}"
        env:
          APLICATION_PORT: "8080"
          AUTHENTICATION_API_KEY: "{{ evolution_api_key }}"
          DATABASE_CONNECTION_URI: "mongodb://{{ mongodb_root_user }}:{{ mongodb_root_password }}@mongodb:27017"
      no_log: true

    - name: 6. Allow Evolution API port through UFW firewall
      ufw:
        rule: allow
        port: "8080"
        proto: tcp