apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
data:
  KC_DB: "postgres"
  KC_DB_URL: "jdbc:postgresql://ip_address:5432/keycloak_dev_db"
  KC_HOSTNAME: "keycloak-dev.k8s.dmc-it-solutions.cloud"
  KC_DB_SCHEMA: "public"
