apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
type: Opaque
stringData:
  KC_DB_USERNAME: ""
  KC_DB_PASSWORD: ""
  KC_BOOTSTRAP_ADMIN_USERNAME: "qadmin"
  KC_BOOTSTRAP_ADMIN_PASSWORD: ""
